# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
#https://www.youtube.com/watch?v=mirZPrWwvao
#Numpy 한번에 제대로 배우기 - youtube by 이수한컴퓨터연구소



---



## 배열 생성

### 리스트로 배열 만들기


In [3]:
d_1 = np.array([1,2,3])
print(d_1)
print(type(d_1))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
d_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
d_2.shape
print(d_2)
d_2[0,0]
d_2[0,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [9]:
d_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
d_3.shape
print(d_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [16]:
np.full((3,3,3,3,3), 1)

array([[[[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]],


        [[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]],


        [[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]]],



       [[[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]],


        [[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]],


        [[[1,

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [19]:
print(np.eye(5, k=1))
print(np.eye(5))

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


* `tri()`: 삼각행렬 생성

In [18]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [27]:
np.empty(10)

array([1.26704218e-311, 1.26709650e-311, 0.00000000e+000, ...,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [33]:
print(d_1)
d_1_zero = np.zeros_like(d_1)
print(d_1_zero)
print(d_1)
d_1_ones = np.ones_like(d_1)
print(d_1_ones)

[1 2 3]
[0 0 0]
[1 2 3]
[1 1 1]


In [34]:
print(d_1)
d_1_full = np.full_like(d_1, 3)
print(d_1_full)

[1 2 3]
[3 3 3]


In [35]:
print(d_1)
d_1_empty = np.empty_like(d_1)
print(d_1_empty)

[1 2 3]
[3 3 3]


### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [37]:
np.arange(0,30,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [41]:
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [46]:
np.logspace(0,10,5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [56]:
np.random.random(100)

array([0.7598721 , 0.73708768, 0.88481936, 0.72654496, 0.87607775,
       0.41528279, 0.56102033, 0.96065279, 0.80993234, 0.41238467,
       0.83910243, 0.4062363 , 0.63521622, 0.22858804, 0.32426011,
       0.56238387, 0.60170099, 0.58377702, 0.73736702, 0.84862608,
       0.43254874, 0.90666225, 0.78375055, 0.9564551 , 0.85996044,
       0.55132656, 0.8049814 , 0.03996279, 0.36992893, 0.91644574,
       0.65872598, 0.44781784, 0.19744666, 0.32553579, 0.295435  ,
       0.50609044, 0.05986376, 0.91653547, 0.80075546, 0.95594965,
       0.48989387, 0.49975679, 0.52265765, 0.09467744, 0.41397077,
       0.47854791, 0.26165853, 0.28566902, 0.69899856, 0.36051586,
       0.77410229, 0.03970521, 0.02893999, 0.59937838, 0.88209171,
       0.34626069, 0.38313378, 0.41050282, 0.81716402, 0.90300133,
       0.85368516, 0.91916023, 0.9016745 , 0.53577254, 0.54012395,
       0.30088562, 0.86858971, 0.18651564, 0.07279902, 0.76685696,
       0.34024688, 0.09717188, 0.65311944, 0.04372242, 0.15554

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [53]:
np.random.randint(0,10,(3,5))

array([[9, 4, 3, 5, 4],
       [5, 7, 6, 5, 2],
       [6, 6, 6, 7, 4]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [52]:
np.random.normal(0,1,(3,3))

array([[ 2.44831102,  0.33406049, -0.56920898],
       [-0.78150094,  0.25923837,  0.27522989],
       [ 0.48810304, -2.68264468,  1.13247901]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [59]:
np.random.rand(3,3)

array([[0.244755  , 0.50936601, 0.91168001],
       [0.18885355, 0.3781078 , 0.19391142],
       [0.00487025, 0.69325496, 0.68870159]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [63]:
np.random.randn(5,5)

array([[-1.42212593, -0.20200639, -1.76633599,  0.8065543 ,  0.92005829],
       [-1.68803175, -0.19930314,  0.5529889 ,  1.47124495,  0.60889282],
       [ 1.22545104, -0.54931157, -1.98847614,  0.70255941, -0.50754367],
       [ 0.48394229, -0.06812394, -0.35889621, -0.03258419,  0.62257229],
       [ 1.41356513, -0.51078522, -0.55262072, -0.13929347, -2.72806636]])

### 표준 데이터 타입

In [67]:
# dtype="<below>"
# bool
# int
# intc
# intp
# int8~64
# float16~64
# uint16~64

In [68]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
print(np.ones((3,3), dtype=bool))
np.full((3,3), 1.0, dtype=float)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [72]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [73]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [74]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [76]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [78]:
def array_info(array):
    print(array)
    print("ndim: ", array.ndim)
    print("shape: ", array.shape)
    print("dtype: ", array.dtype)
    print("size: ", array.size)
    print("itemsize: ", array.itemsize)
    print("nbytes: ", array.nbytes)
    print("strides: ", array.strides)

In [80]:
array_info(d_1)
array_info(d_2)

[1 2 3]
ndim:  1
shape:  (3,)
dtype:  int32
size:  3
itemsize:  4
nbytes:  12
strides:  (4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:  2
shape:  (3, 3)
dtype:  int32
size:  9
itemsize:  4
nbytes:  36
strides:  (12, 4)


### 인덱싱(Indexing)

In [ ]:
print(d_1[-1])
print(d_1[-2])
print(d_1[-3])

In [ ]:
print(d_2[2][1])

In [87]:
print(d_3[-1][2][-1])

9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [90]:
print(d_1)
print(d_1[0:2])
print(d_1[0:])
print(d_1[:2])
print(d_1[::2])
print(d_1[::-1])

[1 2 3]
[1 2]
[1 2 3]
[1 2]
[1 3]
[3 2 1]


In [91]:
print(d_2[:2, :2])
print(d_2[1:, ::-1])
print(d_2[::-1, ::-1])

[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [92]:
print(d_1)
bi = [False, True, False]
print(d_1[bi])

[1 2 3]
[2]


In [107]:
print(d_2)
bi = np.random.randint(0, 2, (3, 3), dtype=bool) # 0, 2 임에 유의
print(bi)
print(d_2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False  True]
 [ True  True  True]
 [ True  True  True]]
[1 3 4 5 6 7 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [97]:
print(d_1)
print([d_1[0], d_1[2]])
idx = [0, 2]
print(d_1[idx])

[1 2 3]
[1, 3]
[1 3]


In [111]:
print(d_2)
idx = np.random.randint(0, 3, (3,3), dtype=int)
print(idx)
print(d_2[0][idx])
print(d_2[1][idx])
print(d_2[2][idx])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 0]
 [1 0 0]
 [2 0 2]]
[[3 3 1]
 [2 1 1]
 [3 1 3]]
[[6 6 4]
 [5 4 4]
 [6 4 6]]
[[9 9 7]
 [8 7 7]
 [9 7 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [114]:
print(d_1)
b_1 = np.insert(d_1, 0, 10)
print(b_1)
print(d_1) 

[1 2 3]
[10  1  2  3]
[1 2 3]


In [115]:
print(d_2)
b_2 = np.insert(d_2, 1, 10, axis=0)
print(b_2)
c_2 = np.insert(d_2, 1, 10, axis=1)
print(c_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [137]:
print(d_1)
d_1[0] = 100
print(d_1)
d_1[0] = 1
print(d_1)
d_1[:2] = [9, 8]
print(d_1)
i = np.array([0,1,2])
d_1[i] = 0
print(d_1)
d_1[0] = 1
d_1[1] = 2
d_1[2] = 3
print(d_1)
d_1 = np.array([1,2,3])

[1 2 3]
[100   2   3]
[1 2 3]
[9 8 3]
[0 0 0]
[1 2 3]


In [138]:
row = np.array([0,1])
col = np.array([1,2])
print(d_2)
d_2[row,col] = 0
print(d_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 3]
 [4 5 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [144]:
print(d_1)
b_1 = np.delete(d_1, 2)
print(b_1)
print(d_1)

[1 2 3]
[1 2]
[1 2 3]


In [148]:
print(d_2)
b_2 = np.delete(d_2, 1, axis=0)
print(b_2)
c_2 = np.delete(d_2, 1, axis=1)
print(c_2)

[[1 0 3]
 [4 5 0]
 [7 8 9]]
[[1 0 3]
 [7 8 9]]
[[1 3]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [159]:
print(d_2)
print(d_2[:2, :2])
d2_sub = d_2[:2, :2] # it is not copy of d_2, just link.
print(d2_sub)
d2_sub[:, 0] = 0
print(d2_sub)
print(d_2)
d_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[[0 2]
 [0 5]]
[[0 2 3]
 [0 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [162]:
print(d_2)
d_2_copy = d_2[:2, :2].copy()
print(d_2_copy)
d_2_copy[0,1] = 100
print(d_2_copy)
print(d_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[  1 100]
 [  4   5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
print(d_2)
d_2_copy = d_2[:2, :2].copy()
print(d_2_copy)
d_2_copy[0,1] = 100
print(d_2_copy)
print(d_2)



---



## 배열 변환

### 배열 전치 및 축 변경

In [163]:
print(d_2)
print(d_2.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [167]:
print(d_3.T)
print()
print(d_3)

[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [171]:
print(d_2.swapaxes(0,1))
print(d_2.swapaxes(1,0))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [173]:
print(d_3.swapaxes(0,1))
print()
print(d_3.swapaxes(1,2))

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]

[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [175]:
d_3.reshape(9,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]],

       [[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]],

       [[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

* `newaxis()`: 새로운 축 추가

In [180]:
d_3.reshape(3,3,3)
d_3[np.newaxis, :2]
print(d_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### 배열 크기 변경

* 배열 모양만 변경

In [184]:
print(d_3)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]

 [[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]

 [[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [186]:
d_1.resize((3,3))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [192]:
np.append(d_1, d_3)
np.append(d_1,d_1,axis=0)
print(d_1)

[1 2 3]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [193]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [194]:
c1 = np.array([3,5,7])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 3, 5, 7])

In [197]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [196]:
np.concatenate([a2,a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [201]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [202]:
np.hstack([a2,a2])


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [205]:
np.dstack([a2,a2]).shape

(2, 3, 2)

* `stack()`: 새로운 차원으로 연결

In [206]:
np.stack([a2,a2]).shape

(2, 2, 3)

### 배열 분할

* `split()`: 배열 분할

In [211]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1)
print(c1)
b,c,d,e,f = np.split(a1, [2,4,6,8])
print(b,c,d,e,f)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [214]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2,c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]] [[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [217]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [220]:
a2 = np.arange(1,10).reshape(3,1,3)
print(a2)
b2,c2 = np.dsplit(a2,[2])
print(b2)
print(c2)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
[[[1 2]]

 [[4 5]]

 [[7 8]]]
[[[3]]

 [[6]]

 [[9]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

### 산술 연산(Arithmetic Operators)

#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

#### 지수와 로그 함수 (Exponential and Log Function)

#### 삼각 함수(Trigonometrical Function)


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

#### cumsum(): 누적합 계산

#### diff(): 차분 계산

#### prod(): 곱 계산

#### cumprod(): 누적곱 계산

#### dot()/matmul(): 점곱/행렬곱 계산

#### tensordot(): 텐서곱 계산

#### cross(): 벡터곱

#### inner()/outer(): 내적/외적

#### mean(): 평균 계산

#### std(): 표준 편차 계산

#### var(): 분산 계산

#### min(): 최소값

#### max(): 최대값

#### argmin(): 최소값 인덱스

#### argmax(): 최대값 인덱스

#### median(): 중앙값

#### percentile(): 백분위 수



#### any()

#### all()

### 비교 연산(Comparison Operators)


#### 불리언 연산자(Boolean Operators)


### 배열 정렬

#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

## 배열 입출력


sample_data




---

